services:
  tcg_frontend:
    # build the same image we tested earlier
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    # mount project into container for live development
    volumes:
      - .:/usr/src/app:delegated
      # ensure host node_modules is ignored inside container
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true   # necessary on some Docker setups for file watching
    command: ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll=2000"]
  tcg_db:
    image: mysql:latest
    restart: no
    environment:                        
      MYSQL_ROOT_PASSWORD: games2026
      MYSQL_DATABASE: tcg_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: games2026
    ports:
      - "3306:3306"
    volumes:
      # - ./init:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
  tcg_backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app:delegated
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

volumes:
  mysql_data:
